# startup_session launch.conf
include ~/.cache/wal/colors-kitty.conf
# include ~/dotfiles/configs/.config/kitty/tokyonight/night.conf

background         #020202

font_family      FantasqueSansM Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

scrollback_indicator_opacity 0.0

# window_padding_width 14
# window_padding_height 14
window_padding_width 0
window_padding_height 0

confirm_os_window_close 0

background_opacity 1.0
