unbind C-b
set -g prefix C-a
bind C-a send-prefix

set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-terminal "screen-256color"
set-option -g focus-events on

set -g history-limit 1000000
set -g set-clipboard on
set -g status-position top
set -g status-bg default
set -g status-style bg=default
set -g status-style fg=default
set -g status-right ""
set -g status-left-length 85
set -g window-status-current-format "#[fg=black,bold bg=default]│#[fg=white bg=cyan]#W#[fg=black,bold bg=default]│"
set -g window-status-current-format "#[fg=black,bold bg=default]│#[fg=colour135 bg=black]#W#[fg=black,bold bg=default]│"
set -g mouse on
set -g base-index 1
set -g pane-base-index 1

set-window-option -g mode-keys vi
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind s set-option -g status
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"

bind Enter copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -r f run-shell "tmux neww ~/dotfiles/scripts/tmux-sessionizer.sh"
bind-key -r k run-shell "~/dotfiles/scripts/tmux-sessionizer.sh ~/dotfiles"
bind-key -n M-l send-keys 'C-l'

set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
