return {
  -- 'nvim-telescope/telescope.nvim',
  -- branch = '0.1.x',
  -- event = 'VeryLazy',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   {
  --     'nvim-telescope/telescope-fzf-native.nvim',
  --     build = 'make',
  --     cond = function()
  --       return vim.fn.executable 'make' == 1
  --     end,
  --   },
  -- },
  -- config = function()
  --   local telescope = require 'telescope'
  --   local builtin = require 'telescope.builtin'
  --   local themes = require 'telescope.themes'
  --   local actions = require 'telescope.actions'
  --
  --   telescope.setup {
  --     defaults = {
  --       mappings = {
  --         i = {
  --           ['<C-u>'] = false,
  --           ['<C-d>'] = false,
  --           ['<esc>'] = actions.close,
  --         },
  --       },
  --     },
  --     extensions = {
  --       fzf = {},
  --     },
  --   }
  --
  --   pcall(telescope.load_extension, 'fzf')
  --
  --   vim.keymap.set('n', '<leader>?', builtin.oldfiles, { desc = 'Find recently opened files' })
  --   vim.keymap.set('n', '<leader><space>', builtin.buffers, { desc = 'Find existing buffers' })
  --   vim.keymap.set('n', '<leader>sh', builtin.help_tags, { desc = 'Search help' })
  --   vim.keymap.set('n', '<leader>sw', builtin.grep_string, { desc = 'Search current word' })
  --   -- vim.keymap.set('n', '<leader>sg', builtin.live_grep, { desc = 'Search by grep' })
  --   vim.keymap.set('n', '<leader>sd', builtin.diagnostics, { desc = 'Search diagnostics' })
  --   vim.keymap.set('n', '<leader>sr', builtin.resume, { desc = 'Search resume' })
  --
  --   vim.keymap.set('n', '<leader>/', function()
  --     builtin.current_buffer_fuzzy_find(themes.get_dropdown { previewer = false })
  --   end, { desc = 'Fuzzily search in current buffer' })
  --
  --   vim.keymap.set('n', '<leader>gf', function()
  --     builtin.git_files(themes.get_dropdown { previewer = false })
  --   end, { desc = 'Search git files' })
  --
  --   vim.keymap.set('n', '<leader>sf', function()
  --     builtin.find_files(themes.get_dropdown { previewer = false })
  --   end, { desc = 'search files' })
  --
  --   local pickers = require 'telescope.pickers'
  --   local finders = require 'telescope.finders'
  --   local make_entry = require 'telescope.make_entry'
  --
  --   vim.keymap.set('n', '<leader>sg', function()
  --     local opts = {}
  --     opts.cwd = vim.uv.cwd()
  --
  --     local finder = finders.new_async_job {
  --       command_generator = function(prompt)
  --         if not prompt or prompt == '' then
  --           return nil
  --         end
  --         local pieces = vim.split(prompt, '  ')
  --         local args = { 'rg' }
  --         if pieces[1] then
  --           table.insert(args, '-e')
  --           table.insert(args, pieces[1])
  --         end
  --         if pieces[2] then
  --           table.insert(args, '-g')
  --           table.insert(args, pieces[2])
  --         end
  --
  --         ---@diagnostic disable-next-line: deprecated
  --         return vim.tbl_flatten {
  --           args,
  --           {
  --             '--color=never',
  --             '--no-heading',
  --             '--with-filename',
  --             '--line-number',
  --             '--column',
  --             '--smart-case',
  --           },
  --         }
  --       end,
  --       entry_maker = make_entry.gen_from_vimgrep(opts),
  --       cwd = opts.cwd,
  --     }
  --
  --     pickers
  --       .new(opts, {
  --         debounce = 100,
  --         prompt_title = 'Search files grep',
  --         finder = finder,
  --         previewer = require('telescope.config').values.grep_previewer(opts),
  --         sorter = require('telescope.sorters').empty(),
  --       })
  --       :find()
  --   end, { desc = 'Search files grep' })
  -- end,
}
